test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

development:
  adapter: postgresql
  encoding: utf8
  database: sample_development
  username: csc
  password: "123456"
  timeout: 5000


production:
  adapter: postgresql
  encoding: utf8
  database: sample_production
  host: localhost
  username: csc
  password: "123456"
  timeout: 5000
