test: &test
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

development:
  adapter: postgresql
  encoding: utf8
  database: sample_development
  username: csc
  password: "123456"
  timeout: 5000

#development:
#  adapter: mysql2
#  database: sample_development
#  encoding: utf8
#  username: root
#  password: "123456"
#  socket: /var/run/mysqld/mysqld.sock


production:
  adapter: postgresql
  encoding: utf8
  database: sample_production
  host: localhost
  username: csc
  password: "123456"
  timeout: 5000

cucumber:
  <<: *test